### ISSUE TITLE
challenge and id tokens are Base64Url not Base64

### ISSUE THREAD

**Issue by chops888** [asbiin/laravel-webauthn#330]
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at WebAuthn._bufferDecode (/vendor/webauthn/webauthn.js:133:18)
    at WebAuthn.sign (/vendor/webauthn/webauthn.js:77:40)
    at HTMLDocument.<anonymous> (/webauthn/auth:192:12)
    at mightThrow (eval at <anonymous> /js/app.js:72:1), <anonymous>:3578:29)
    at process (eval at <anonymous> (/js/app.js:72:1), <anonymous>:3646:12)

Server-side. if I modify 

PublicKeyCredentialRequestOptions.php:167
 [-] 'challenge' => Base64Url::encode($this->challenge),
 [+] 'challenge' => base64_encode($this->challenge),

and 

PublicKeyCredentialDescriptor.php:104
[-] 'id' => Base64Url::encode($this->id),
[+] 'id' => base64_encode($this->id),

window.atob completes successfully, and I can authenticate.

Alternately, client-side, if I add a function to pre-decode from Base64Url to Base64 before calling window.atob, then I can authenticate successfully:

webauth.js:133
[-]   var t = window.atob(value);
 [+] var t = window.atob(this.preDecodeBase64Url(value));

And helper function: 

WebAuthn.prototype.preDecodeBase64Url = function (input) {

    // Replace non-url compatible chars with base64 standard chars
    input = input
        .replace(/-/g, '+')
        .replace(/_/g, '/');

    // Pad out with standard base64 required padding characters
    var pad = input.length % 4;
    if(pad) {
        if(pad === 1) {
            throw new Error('InvalidLengthError: Input base64url string is the wrong length to determine padding');
        }
        input += new Array(5-pad).join('=');
    }

    return input;

}

**Comment by chops888** [comment]
Ack, Even though I'd run composer update to the latest version, I now see webauthn.js here has the Base64Url decoding that I implemented above. Measure once, cut twice...
