### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'WebAuthn')     at webauthn.js:220:188     at webauthn.js:220:191

### ISSUE THREAD

**Issue by ppmint1** [asbiin/laravel-webauthn#451]
I am using VUE3 as frontend and trying to import webauthn.js from the vendor like this

<script> import '../../../../vendor/asbiin/laravel-webauthn/resources/js/webauthn'; ....

But I get an error

Uncaught TypeError: Cannot set properties of undefined (setting 'WebAuthn') at webauthn.js:220:188 at webauthn.js:220:191
    

how to fix it?
Thanks :)

**Comment by ppmint1** [comment]
Saya mencoba menggunakan https://simplewebauthn.dev/docs/packages/browser dan itu bekerja
