### ISSUE TITLE
Registering a webauthn key (touch id and passkey tried) fails when using @simplewebauthn/browser

### ISSUE THREAD

**Issue by matthijs** [asbiin/laravel-webauthn#472]
Hi,

We are using @simplewebauthn/browser in our project to register webauthn keys and to login to our service. But when using this project it fails to register the key with the following error:

```php
[2024-02-02 15:08:34] local.INFO: Trying to load data from an array {"data":{"id":"<cut>","rawId":"<cut>","response":{"attestationObject":"<random characters>","clientDataJSON":"<more random characters>","transports":["internal"],"publicKeyAlgorithm":-7,"publicKey":"<public key>","authenticatorData":"<more characters>"},"type":"public-key"}}
[2024-02-02 15:08:34] local.INFO: Trying to load the data {"data":"<more characters>"}
[2024-02-02 15:08:34] local.INFO: Loading the Attestation Statement
[2024-02-02 15:08:34] local.INFO: Attestation Statement loaded
[2024-02-02 15:08:34] local.DEBUG: Attestation Statement loaded {"attestationStatement":{"Webauthn\\AttestationStatement\\AttestationStatement":{"fmt":"none","attStmt":[],"trustPath":{"type":"Webauthn\\TrustPath\\EmptyTrustPath"},"type":"none"}}}
[2024-02-02 15:08:34] local.INFO: Attestation Object loaded
[2024-02-02 15:08:34] local.DEBUG: Attestation Object {"ed":{"Webauthn\\AttestationStatement\\AttestationObject":{"metadataStatement":null,"rawAttestationObject":"<more characters>","attStmt":{"fmt":"none","attStmt":[],"trustPath":{"type":"Webauthn\\TrustPath\\EmptyTrustPath"},"type":"none"},"authData":{"authData":"<cut>�H�ny��@��\u0011\u0011o~�I\u0000\u0010>��)1�F\"��j6h6��\u0001\u0002\u0003& \u0001!X 4<cut>","rpIdHash":"<cut>a~�y�\u0018v\u0013���_n</cut>","flags":"E","signCount":0,"attestedCredentialData":{"aaguid":"<uuid>","credentialId":"<characters>","credentialPublicKey":"<public key>"},"extensions":null}}}}
[2024-02-02 15:08:34] local.INFO: The data has been loaded
[2024-02-02 15:08:34] local.DEBUG: Public Key Credential {"publicKeyCredential":{"Webauthn\\PublicKeyCredential":"{\"type\":\"public-key\",\"id\":\"<some id>\",\"transports\":[\"internal\"]}"}}
[2024-02-02 15:08:34] local.DEBUG: Webauthn publicKey deserialize error {"exception":"[object] (JsonException(code: 4): Syntax error at /projecten/frontend/vendor/asbiin/laravel-webauthn/src/Services/Webauthn/CredentialAttestationValidator.php:51)
[stacktrace]
#0 /projecten/frontend/vendor/asbiin/laravel-webauthn/src/Services/Webauthn/CredentialAttestationValidator.php(51): json_decode('', true, 512, 4194304)
#1 /projecten/frontend/vendor/asbiin/laravel-webauthn/src/Services/Webauthn/CredentialAttestationValidator.php(40): LaravelWebauthn\\Services\\Webauthn\\CredentialAttestationValidator->pullPublicKey(Object(App\\Models\\User))
#2 /projecten/frontend/vendor/asbiin/laravel-webauthn/src/Services/Webauthn.php(143): LaravelWebauthn\\Services\\Webauthn\\CredentialAttestationValidator->__invoke(Object(App\\Models\\User), Array)
#3 /projecten/frontend/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): LaravelWebauthn\\Services\\Webauthn::validateAttestation(Object(App\\Models\\User), Array, 'bla')
```

Hopefully this gives a pointer on where to search whats going on.

The post to the register/options succeeds and I get a publicKey object with the required info. But the register fails with the error as stated above.

**Comment by matthijs** [comment]
Ok, this is my fault, the relying party id was incorrect.
